In [3]:
import pandas as pd

df = pd.read_csv("Comprehensive_Banking_Database.csv")
df.head(5)
# df.isna()

,Customer ID,First Name,Last Name,Age,Gender,Address,City,Contact Number,Email,Account Type,...,Credit Card Balance,Minimum Payment Due,Payment Due Date,Last Credit Card Payment Date,Rewards Points,Feedback ID,Feedback Date,Feedback Type,Resolution Status,Resolution Date
0,1,Joshua,Hall,45,Male,Address_1,Fort Worth,19458794854,joshua.hall@kag.com,Current,...,4524.32,226.22,11/26/2023,3/20/2023,8142,1,10/6/2023,Suggestion,Resolved,1/22/2023
1,2,Mark,Taylor,47,Female,Address_2,Louisville,19458794855,mark.taylor@kag.com,Current,...,856.70,42.84,11/5/2023,6/16/2023,4306,2,4/7/2023,Complaint,Resolved,8/27/2023
2,3,Joseph,Flores,25,Female,Address_3,Philadelphia,19458794856,joseph.flores@kag.com,Current,...,3242.36,162.12,1/8/2023,3/20/2023,4842,3,9/7/2023,Praise,Pending,5/11/2023
3,4,Kevin,Lee,52,Other,Address_4,Oklahoma City,19458794857,kevin.lee@kag.com,Savings,...,4329.17,216.46,9/8/2023,10/15/2023,9463,4,5/28/2023,Complaint,Resolved,7/5/2023
4,5,Linda,Johnson,68,Other,Address_5,Phoenix,19458794858,linda.johnson@kag.com,Savings,...,25.72,1.29,3/4/2023,7/27/2023,2209,5,2/12/2023,Complaint,Resolved,11/21/2023

In [13]:
# What are the most common types of transactions (e.g., withdrawals, deposits, transfers)
# Count occurrences of each transaction type


transaction_counts = df['Transaction Type'].value_counts()

# Convert the result to a DataFrame for better display
transaction_counts_df = transaction_counts.reset_index()
transaction_counts_df.columns = ['transaction_type', 'count']
transaction_counts_df = transaction_counts_df.sort_values(by='count', ascending=False)

print(transaction_counts_df)

  transaction_type  count
0          Deposit   1698
1       Withdrawal   1673
2         Transfer   1629

In [19]:
# Who are the top 10 customers with the highest account balances

top_10_customers = df.nlargest(10 , 'Account Balance')

top_10_customers.head(10)

# print(top_10_customers['First Name', 'Account Balance'])

# What are the top 10 customers with the highest average transaction amounts

,Customer ID,First Name,Last Name,Age,Gender,Address,City,Contact Number,Email,Account Type,...,Credit Card Balance,Minimum Payment Due,Payment Due Date,Last Credit Card Payment Date,Rewards Points,Feedback ID,Feedback Date,Feedback Type,Resolution Status,Resolution Date
4055,4056,Mark,Flores,46,Male,Address_4056,San Jose,19458798909,mark.flores@kag.com,Savings,...,4332.80,216.64,3/6/2023,12/24/2023,6883,4056,6/29/2023,Suggestion,Resolved,2/22/2023
3881,3882,Andrew,Moore,32,Male,Address_3882,Denver,19458798735,andrew.moore@kag.com,Current,...,502.89,25.14,8/30/2023,12/11/2023,5013,3882,12/14/2023,Complaint,Resolved,9/30/2023
292,293,Michael,Carter,46,Other,Address_293,Baltimore,19458795146,michael.carter@kag.com,Savings,...,1612.06,80.60,4/6/2023,10/29/2023,2322,293,3/19/2023,Suggestion,Pending,12/31/2023
370,371,Andrew,Smith,22,Other,Address_371,Philadelphia,19458795224,andrew.smith@kag.com,Savings,...,3096.80,154.84,9/5/2023,9/25/2023,287,371,4/25/2023,Complaint,Resolved,1/25/2023
4983,4984,Barbara,Garcia,47,Other,Address_4984,Seattle,19458799837,barbara.garcia@kag.com,Savings,...,860.32,43.02,8/17/2023,1/6/2023,4946,4984,11/18/2023,Suggestion,Pending,10/28/2023
4030,4031,Kimberly,King,22,Other,Address_4031,Fort Worth,19458798884,kimberly.king@kag.com,Current,...,411.52,20.58,7/12/2023,2/23/2023,1951,4031,8/31/2023,Complaint,Pending,10/22/2023
2253,2254,Betty,Campbell,67,Other,Address_2254,Nashville,19458797107,betty.campbell@kag.com,Savings,...,4891.25,244.56,8/20/2023,11/20/2023,5970,2254,3/19/2023,Suggestion,Resolved,7/5/2023
27,28,Amanda,Hill,60,Female,Address_28,Oklahoma City,19458794881,amanda.hill@kag.com,Savings,...,1530.42,76.52,11/16/2023,7/31/2023,2965,28,12/21/2023,Complaint,Pending,2/23/2023
2958,2959,Mary,Miller,57,Female,Address_2959,Albuquerque,19458797812,mary.miller@kag.com,Current,...,3061.15,153.06,6/10/2023,1/12/2023,9631,2959,8/16/2023,Complaint,Pending,1/6/2023
959,960,Matthew,Campbell,25,Other,Address_960,Louisville,19458795813,matthew.campbell@kag.com,Current,...,2706.00,135.30,7/15/2023,1/29/2023,4968,960,2/11/2023,Complaint,Resolved,9/11/2023